name: Call apply-terrafom from main branch

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

jobs:
  apply-tf:
    uses: ./.github/workflows/apply_terraform.yml
    with:
      workspace_name: 'skyboy'
      listeners: 'mainlisteners'
    secrets:
      image_uri: ${{ secrets.PROD_IMAGE_URI }}
      tf_token: ${{ secrets.TERRAFORM_TOKEN }}
